[theme]
base="light"
primaryColor="#17A9CE"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F5FBF5"
textColor="#31333F"
font="sans serif"
CUSTOM_COLORS = ["#1B3F7D", "#2D66A7", "#498ABA", "#6AB1CF", "#8ECAC4", "#B3DBB8"]